language: python
python:
    - "3.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio run
    - cp -v .pio/build/megaADK/firmware.hex megaadk-firmware.hex

deploy:
    provider: releases
    api_key: ${api_key}
    file: "megaadk-firmware.hex"
    skip_cleanup: true
    on:
        tags: true
